### ISSUE TITLE
renames first same type ending tag, not appropriate pairing tag

### ISSUE THREAD

**Issue by tomchovanec** [formulahendry/vscode-auto-rename-tag#16]
```
    **<md-** *ngFor="let productPrice of model.productPrices">  // <-- started replacing DIV tag
      <div layout="row" layoutSm="column" layoutXs="column" >
        <md-input placeholder="Location" [(ngModel)]="productPrice.location" readonly flex></md-input>
        <md-input placeholder="Purchase Price" [(ngModel)]="productPrice.purchasePrice" readonly flex></md-input>
       **</md->**  //  <-- renames first, not pairing DIV tag - FAIL
       <div layout="row" layoutSm="column" layoutXs="column" >
        <md-input placeholder="Retail Price 1" [(ngModel)]="productPrice.retailPrice1" readonly flex></md-input>
        <md-input placeholder="Retail Price 2" [(ngModel)]="productPrice.retailPrice2" readonly flex></md-input>
        <md-input placeholder="Retail Price 3" [(ngModel)]="productPrice.retailPrice3" readonly flex></md-input>
       </div>
     **</div>** //  <-- should rename this tag
```

**Comment by formulahendry** [comment]
I could not repro it. Are you using latest version?
![rename](https://cloud.githubusercontent.com/assets/1050213/21016964/9cb24604-bda2-11e6-9438-0d4d95690861.gif)

**Comment by tomchovanec** [comment]
steps to reproduce:
1) double click on begin tag (so it's selected)
2) start to overwrite (not just adding 12)
   - but your samle doesn't work correctly for me as well... maybe I could
try to reinstall


[image: Vložený obrázek 1]

2016-12-08 17:01 GMT+01:00 Jun Han <notifications@github.com>:

**Comment by Deilan** [comment]
#20

**Comment by Romane-T** [comment]
Up till now, has been working perfectly. Then, 2 days ago, it started doing as described here (this thread) and as in thread #20 . Today, non-functional at all.

Same steps to reproduce as report from @tomchovanec above.

Have tried a number of times by closing then reopening Code, which in the past has fixed problems with extensions not working. This "fix" now (today) does not work for this extension, though it did when the issue started about two days ago. Tried a reboot, same failure.

Latest version of Code. Latest version of Extension. Operating system fully up to date (Linux, Debian Testing, XFCE desktop)

Have noticed that where previously both starting and ending tag were selected on the double-click of the opening tag, now only the starting tag is selected.

**Comment by formulahendry** [comment]
Could you go to `Help` -> `Toggle Developer Tools`, and see if there is any error message in `Console`?

![image](https://cloud.githubusercontent.com/assets/1050213/25554347/a0af0a7e-2cfd-11e7-8f65-e53b6d7185c8.png)

**Comment by Romane-T** [comment]
Good morning

A little more information which leads me to think that the issue may not 
actually be the extension, but related more to (perhaps?) Code, to the 
operating system, or to a combination of both (or maybe even something 
else again).

Sorry if one dribbles a little here; thinking as one types. The main 
reason that discuss all this here is that as a developer you may have a 
better idea where this may be best passed, and also indirectly some 
tests that you can attempt and/or have others who report this issue to try.

When this error occurred, my computer had been running a chore for a 
number of days (close to a week, probably), thus not shut down overnight 
as usual. This chore finished yesterday, so last night, the computer was 
shut down again overnight. On starting the computer this morning, the 
extension worked flawlessly, thus no point yet looking for any error 
message (and by implication, no point trying a re-install of the 
extension). But this very fact that after a number of hours with the 
computer shut down the extension functioned again as designed, and that 
the failure of the extension went through a process of deterioration 
before completely failing, very strongly suggests to these eyes that the 
issue is not so much the extension but possibly as have suggested above.

Why didn't this happen after a simple reboot? One's suggestion is that 
the longer shut-down time may clear whatever "electronic" "thing" has or 
is getting its twisteds in a nicker in (memory?). Which suggests, again, 
that the problem lies elsewhere, and that perhaps time to drink a cup of 
coffee may also be sufficient (or overly sufficient) time for a shut-down.

Yes, should the extension play up again, then the opportunity will be 
there to see if any error messages which one can report, as these may 
point more directly to the actual culprit.

If one may intrude another thought, albeit related, one has been 
frustrated often by various extensions failing during the course of the 
working day (anything up to twelve hours, give or take - I'm retired, so 
my time is my own). A simple shut-down of Code and re-starting it fixes 
this for a time every time so far, till this - so never bothered with 
filing any reports (besides which, have utterly no idea where would make 
said report). This suggests to Romane that the problem lies somewhere 
else, and he suspects (without proof) that it may be in Code itself. The 
question is asked - does Code go wandering with inattention when left 
running for a period of time?

Thank you for listening. When or if get error messages, will report them 
here.

Romane

**Comment by Romane-T** [comment]
Ok, spoke too soon. Complete failure again. But...

There are errors in the Console for another extension - vscode-colorize 
(kamiKillertO). As these errors directly relate to that extension, have 
raised an issue there, including the error messages.

Rather than retype etc. am putting only a link to those error messages 
here. Am theorising that possibly (allow me to be wrong :) ) the two 
issues are inter-related. Yay or nay is left in yours and kamiKillertO's 
hands.

https://github.com/KamiKillertO/vscode-colorize/issues/35

There is another error when Code starts. It varies a little, but in the 
main (have zero idea if related) all the following is in red:

//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 
[Extension Host] Error: spawn git ENOENT
     at exports._errnoException (util.js:1026:11)
     at Process.ChildProcess._handle.onexit 
(internal/child_process.js:193:32)
     at onErrorNT (internal/child_process.js:359:16)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
     at process._tickCallback 
(internal/process/next_tick.js:98:9)d.logExtensionHostMessage @ 
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29
//usr/share/code/resources/app/out/vs/workbench/electron-browser/workbench.main.js:29 
[Extension Host] Looking for parseable documents...

Romane

**Comment by MonsieurMan** [comment]
I got this when it began doing the same thing : 

`
Illegal value for `line`: Error: Illegal value for `line`
    at t._lineAt (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:229497)
    at Object.lineAt (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:228287)
    at TagManager.getNewWord (C:\Users\Codin\.vscode\extensions\formulahendry.auto-rename-tag-0.0.11\out\src\tagManager.js:88:33)
    at TagManager.updatePairedTag (C:\Users\Codin\.vscode\extensions\formulahendry.auto-rename-tag-0.0.11\out\src\tagManager.js:81:27)
    at vscode.workspace.onDidChangeTextDocument.event (C:\Users\Codin\.vscode\extensions\formulahendry.auto-rename-tag-0.0.11\out\src\tagManager.js:13:18)
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:30930)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:34737)
    at t.$acceptModelChanged (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:298227)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:266430)
    at s (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:154933)
`

**Comment by alextegelid** [comment]
For me it seems Auto Rename Tag correctly renames the `div` tag to an `a` (as in the first letter of `article`) then switches over to renaming a matching `a` tag not the initial `div` tag I started renaming. What's funny is that if the extension is checking for a new matching tag for each keystroke the matching `a` tag should be the one that was just created by typing the first a.

Perhaps a solution to this could be to not search for a new matching tag until the cursor is repositioned with either a mouse click or pressing the arrow keys etc.

I'm attaching the highly simplified WordPress template markup below as well as a demo video.

```
<div class="post-entry">

	<a href="#">
		<div class="post-thumbnail">
			<img src="" alt="">
		</div>
	</a>

	<h1 class="post-title"><?php the_title(); ?></h1>

	<a href="<?php the_permalink(); ?>">
		Lorem
	</a>

</div>
```

![screen recording 2018-03-13 at 02 40 em](https://user-images.githubusercontent.com/7058721/37345197-acf4e23a-26cc-11e8-9a2d-13e6137f75c3.gif)

**Comment by capaj** [comment]
I have the same error as @MonsieurMan 
```
  ERR Illegal value for `line`: Error: Illegal value for `line`
    at t._lineAt (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:377:34)
    at Object.lineAt (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:375:860)
    at TagManager.getNewWord (/home/capaj/.vscode/extensions/formulahendry.auto-rename-tag-0.0.15/out/src/tagManager.js:97:33)
    at TagManager.updatePairedTag (/home/capaj/.vscode/extensions/formulahendry.auto-rename-tag-0.0.15/out/src/tagManager.js:90:27)
    at __dirname.run.vscode.workspace.onDidChangeTextDocument.event (/home/capaj/.vscode/extensions/formulahendry.auto-rename-tag-0.0.15/out/src/tagManager.js:14:18)
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
    at e.$acceptModelChanged (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:538:1008)
    at t._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:837)
    at t._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:658:509)
    at t._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:657:126)
    at t._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:656:59)
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:653:895
    at /usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:130:793
    at e.fire (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:133:218)
    at a (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:186:147)
    at Socket.n._socketDataListener (/usr/share/code/resources/app/out/vs/workbench/node/extensionHostProcess.js:186:368)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```
