### ISSUE TITLE
Illegal value for `line`: Error: Illegal value for `line`

### ISSUE THREAD

**Issue by kurtextrem** [formulahendry/vscode-auto-rename-tag#24]
Illegal value for `line`: Error: Illegal value for `line`
    at t._lineAt (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:229497)
    at Object.lineAt (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:228287)
    at TagManager.getWordAtPosition (C:\Users\admin\.vscode-insiders\extensions\formulahendry.auto-rename-tag-0.0.11\out\src\tagManager.js:32:33)
    at TagManager.getCurrentWord (C:\Users\admin\.vscode-insiders\extensions\formulahendry.auto-rename-tag-0.0.11\out\src\tagManager.js:28:25)
    at vscode.window.onDidChangeTextEditorSelection.event (C:\Users\admin\.vscode-insiders\extensions\formulahendry.auto-rename-tag-0.0.11\out\src\tagManager.js:10:18)
    at e.invoke (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:30930)
    at e.fire (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:34737)
    at t.$acceptSelectionsChanged (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:347776)
    at t.e.handle (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:266430)
    at s (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:154933)
    at h (c:\Program Files (x86)\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:4:155610)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by formulahendry** [comment]
Hi @kurtextrem , could you please show me the repro steps and what's the impact of this error message?

**Comment by kurtextrem** [comment]
I don't really know, I saw it in the Dev Tools so I went ahead to report it. It might occur in invalid JavaScript files (where I'm currently editing and the syntax is wrong)
There is no impact I'd say - auto renaming works afterwards.

**Comment by formulahendry** [comment]
This issue should be fixed in latest version. Let me know if you meet with the error again.

**Comment by jtsom** [comment]
I'm seeing this error in the latest version, in an Angular project.

```
shell.ts:419 [formulahendry.auto-rename-tag] Illegal value for `line`: Error: Illegal value for `line`
	at t._lineAt (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:255448)
	at Object.lineAt (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:254227)
	at TagManager.getNewWord (C:\Users\John Tsombakos\.vscode-insiders\extensions\formulahendry.auto-rename-tag-0.0.14\out\src\tagManager.js:96:33)
	at TagManager.updatePairedTag (C:\Users\John Tsombakos\.vscode-insiders\extensions\formulahendry.auto-rename-tag-0.0.14\out\src\tagManager.js:89:27)
	at vscode.workspace.onDidChangeTextDocument.event (C:\Users\John Tsombakos\.vscode-insiders\extensions\formulahendry.auto-rename-tag-0.0.14\out\src\tagManager.js:14:18)
	at e.invoke (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:57534)
	at e.fire (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:59325)
	at e.$acceptModelChanged (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:354965)
	at t.e.invoke (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:433986)
	at e._invokeHandler (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:28:284174)
```

**Comment by Cxb0426** [comment]
Did I encounter the same problem again.
