### ISSUE TITLE
Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by v2beta** [formulahendry/vscode-auto-rename-tag#29]
Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined
    at TagManager.updatePairedTag (/Users/imac/.vscode/extensions/formulahendry.auto-rename-tag-0.0.12/out/src/tagManager.js:64:70)
    at vscode.workspace.onDidChangeTextDocument.event (/Users/imac/.vscode/extensions/formulahendry.auto-rename-tag-0.0.12/out/src/tagManager.js:14:18)
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:14715)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:53565)
    at t.$acceptDirtyStateChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:343547)
    at t.$acceptModelSaved (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:343330)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:312304)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:176531)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:177208)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)

---

Illegal value for `line`: Error: Illegal value for `line`
    at t._lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:254412)
    at Object.lineAt (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:253202)
    at TagManager.getWordAtPosition (/Users/imac/.vscode/extensions/formulahendry.auto-rename-tag-0.0.12/out/src/tagManager.js:33:33)
    at TagManager.getCurrentWord (/Users/imac/.vscode/extensions/formulahendry.auto-rename-tag-0.0.12/out/src/tagManager.js:29:25)
    at vscode.window.onDidChangeTextEditorSelection.event (/Users/imac/.vscode/extensions/formulahendry.auto-rename-tag-0.0.12/out/src/tagManager.js:11:18)
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:14715)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:53565)
    at t.$acceptSelectionsChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:391342)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:312304)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:176531)

**Comment by formulahendry** [comment]
This issue should be fixed in latest version. Let me know if you meet with the error again.
